from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from prototype.llm_nvidia import call_nvidia_chat_completions
from prototype.report_schema import CallGradingReport, CallMetadata, DIMENSIONS, parse_scorecard


FOOTER_DISCLAIMER = (
    "Generated by AI Quality Assurance System | For supervisory review only | Not for disciplinary action "
    "without human review"
)


def _strip_code_fences(s: str) -> str:
    s = s.strip()
    if s.startswith("```"):
        # Remove opening fence (e.g. ```json) and closing fence (```)
        lines = s.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]  # Remove opening fence line
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]  # Remove closing fence line
        s = "\n".join(lines)
    return s.strip()


def _extract_balanced_json_object(s: str) -> str:
    """
    Extract the first top-level JSON object from a model response.

    This is more robust than searching for the first '{' and last '}' because it:
    - tracks brace depth
    - avoids counting braces inside quoted strings
    """
    s = _strip_code_fences(s)
    depth = 0
    start_idx: Optional[int] = None

    in_string = False
    escape = False

    for i, ch in enumerate(s):
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
            continue

        if ch == "{":
            if depth == 0:
                start_idx = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start_idx is not None:
                    return s[start_idx : i + 1]

    raise ValueError("Could not find a balanced JSON object in the model response.")


def parse_json_object(s: str) -> Dict[str, Any]:
    try:
        return json.loads(_extract_balanced_json_object(s))
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to decode JSON from model response: {e}") from e


def _step1_extract_evidence_prompt(transcript_text: str, call_type_hint: str) -> List[Dict[str, str]]:
    system = (
        "You are a careful assistant that extracts structured evidence from emergency call transcripts for quality "
        "assessment. Return JSON only."
    )
    user = f"""
Analyze the behavioral-health related emergency call transcript below.

Transcript:
{transcript_text}

Call type hint: {call_type_hint}

Return ONLY valid JSON with this schema:
{{
  "call_type": string,
  "location_provided": boolean,
  "location_clarified": boolean,
  "breathing_or_consciousness_assessed": boolean,
  "naloxone_access_assessed": boolean,
  "prearrival_instructions_present": boolean,
  "good_samaritan_disclosure_present": boolean,
  "behavioral_health_diversion_screening_present": boolean,
  "dispatch_behavior": {{
    "primary_response": "medical_response"|"behavioral_health_unit"|"law_enforcement"|"other",
    "evidence": string
  }},
  "caller_management": {{
    "kept_on_line": boolean,
    "empathy_evidence": string,
    "clear_next_steps": boolean
  }},
  "information_completeness": {{
    "time_estimate_provided": boolean,
    "individual_description_provided": boolean,
    "number_of_individuals_affected_provided": boolean,
    "substances_or_paraphernalia_observed_provided": boolean
  }},
  "evidence_snippets": [
    {{
      "label": string,
      "snippet": string
    }}
  ],
  "critical_flags": [string]
}}

Notes:
- If something is not mentioned, use false or empty strings/lists accordingly.
- Do not include any extra keys.
"""
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def _step2_scorecard_prompt(
    *,
    transcript_text: str,
    call_type_hint: str,
    evidence_json: Dict[str, Any],
) -> List[Dict[str, str]]:
    system = (
        "You are a quality-assurance rater for emergency behavioral-health calls. "
        "Use rubric dimensions to score evidence. Return JSON only."
    )

    rubric_dimensions = [
        {"name": "Address & Location", "weight_percent": 10},
        {"name": "Medical Assessment", "weight_percent": 15},
        {"name": "Naloxone Inquiry", "weight_percent": 15},
        {"name": "Pre-Arrival Instructions", "weight_percent": 15},
        {"name": "Good Samaritan Disclosure", "weight_percent": 10},
        {"name": "Dispatch Accuracy", "weight_percent": 10},
        {"name": "Behavioral Health Diversion", "weight_percent": 10},
        {"name": "Caller Management", "weight_percent": 10},
        {"name": "Information Completeness", "weight_percent": 5},
    ]

    footer = FOOTER_DISCLAIMER

    scoring_anchors = {
        "Address & Location": {
            "5": "Exact address/location confirmed early; clarified ambiguity.",
            "3": "Partial location (intersection/landmark) but not fully confirmed/clarified.",
            "1": "No usable location or operator did not clarify.",
        },
        "Medical Assessment": {
            "5": "Assessed breathing/consciousness and asked follow-ups; identified key medical indicators.",
            "3": "Asked at least once but limited follow-up or accepted uncertainty without probing.",
            "1": "Did not assess breathing/consciousness or key indicators.",
        },
        "Naloxone Inquiry": {
            "5": "Explicitly asked about naloxone availability promptly when appropriate.",
            "3": "Asked late or indirectly.",
            "1": "Never asked.",
        },
        "Pre-Arrival Instructions": {
            "5": "Gave clear, appropriate pre-arrival instructions (airway/breathing/rescue steps) and safety guidance.",
            "3": "Some instructions given but incomplete or not tailored to situation.",
            "1": "No pre-arrival instructions.",
        },
        "Good Samaritan Disclosure": {
            "5": "Proactively explained Good Samaritan protections when caller hesitated or as reassurance.",
            "3": "Mentioned generally but not tied to caller concerns.",
            "1": "Not mentioned when relevant.",
        },
        "Dispatch Accuracy": {
            "5": "Dispatched correct primary response type promptly (medical response for medical emergency).",
            "3": "Dispatched but with some ambiguity/delay.",
            "1": "Wrong response type (e.g., only law enforcement) or unclear dispatch.",
        },
        "Behavioral Health Diversion": {
            "5": "Appropriately identified whether BH diversion applies; used screening questions or justified non-diversion.",
            "3": "Some consideration but limited screening/justification.",
            "1": "No screening/consideration; defaulted response without assessment.",
        },
        "Caller Management": {
            "5": "Kept caller engaged/on the line; calm tone; clear next steps; reassurance.",
            "3": "Some reassurance but limited engagement or abrupt transitions.",
            "1": "Abrupt end/no guidance; did not manage caller.",
        },
        "Information Completeness": {
            "5": "Collected key details: number affected, substances/paraphernalia, description, timing when relevant.",
            "3": "Collected some details but missed multiple key items.",
            "1": "Minimal information gathered.",
        },
    }

    user = f"""
Create the behavioral-health call quality assessment report for the transcript.

Call type hint: {call_type_hint}

Transcript:
{transcript_text}

Step 1 evidence (use this as your source of truth when possible):
{json.dumps(evidence_json, indent=2)}

Scoring rubric dimensions (score_out_of_5 should reflect how well the operator met each dimension):
{json.dumps(rubric_dimensions, indent=2)}

Scoring anchors (use these to standardize scores; choose 1/3/5 when possible and justify any 2/4 scores):
{json.dumps(scoring_anchors, indent=2)}

Return ONLY valid JSON with this schema:
{{
  "overall_score_out_of_5": number,
  "dimension_scores": [
    {{
      "name": string,
      "weight_percent": number,
      "score_out_of_5": number,
      "evidence_and_notes": {{
        "evidence": string,
        "notes": string
      }}
    }}
  ],
  "strengths": [string],
  "areas_for_improvement": [string],
  "critical_flags": [string],
  "coaching_recommendation": string,
  "footer_disclaimer": "{footer}"
}}

Rules:
- dimension_scores must include ALL rubric dimension names exactly.
- strengths, areas_for_improvement should include at least 3 items total combined.
- Keep evidence specific and grounded in transcript language.
- If critical_flags are empty, return [].
"""
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def _clamp(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))


def _apply_standardization_rules(
    dimension_scores: Dict[str, Dict[str, Any]],
    evidence_json: Dict[str, Any],
    call_type_hint: str,
) -> Dict[str, Dict[str, Any]]:
    """
    Deterministic guardrails to reduce variability.
    We cap/force certain dimension scores based on extracted evidence flags.
    """
    def set_score(name: str, *, force: Optional[float] = None, cap: Optional[float] = None) -> None:
        if name not in dimension_scores:
            return
        s = float(dimension_scores[name].get("score_out_of_5", 0))
        if force is not None:
            s = force
        if cap is not None:
            s = min(s, cap)
        dimension_scores[name]["score_out_of_5"] = _clamp(s, 1.0, 5.0)

    location_provided = bool(evidence_json.get("location_provided"))
    location_clarified = bool(evidence_json.get("location_clarified"))
    breathing_assessed = bool(evidence_json.get("breathing_or_consciousness_assessed"))
    naloxone_assessed = bool(evidence_json.get("naloxone_access_assessed"))
    prearrival = bool(evidence_json.get("prearrival_instructions_present"))
    samaritan = bool(evidence_json.get("good_samaritan_disclosure_present"))
    diversion = bool(evidence_json.get("behavioral_health_diversion_screening_present"))
    dispatch = evidence_json.get("dispatch_behavior", {}) or {}
    primary_response = str(dispatch.get("primary_response", "")).lower()
    caller_mgmt = evidence_json.get("caller_management", {}) or {}
    kept_on_line = bool(caller_mgmt.get("kept_on_line"))
    clear_next = bool(caller_mgmt.get("clear_next_steps"))
    info = evidence_json.get("information_completeness", {}) or {}

    # Address & Location
    if not location_provided:
        set_score("Address & Location", force=1.0)
    elif location_provided and not location_clarified:
        set_score("Address & Location", cap=3.0)

    # Medical Assessment
    if not breathing_assessed:
        set_score("Medical Assessment", cap=2.0)

    # Naloxone Inquiry (when likely relevant)
    likely_overdose = any(
        k in call_type_hint.lower() for k in ["overdose", "person down", "unknown medical", "unresponsive"]
    )
    if likely_overdose and not naloxone_assessed:
        set_score("Naloxone Inquiry", force=1.0)

    # Pre-arrival
    if not prearrival:
        set_score("Pre-Arrival Instructions", cap=2.0)

    # Good Samaritan (only cap if we think it was relevant; for prototype, treat as generally relevant)
    if not samaritan:
        set_score("Good Samaritan Disclosure", cap=3.0)

    # Dispatch accuracy
    if likely_overdose and primary_response in ["law_enforcement", "other", ""]:
        set_score("Dispatch Accuracy", cap=2.0)

    # Behavioral health diversion (cap if no screening/justification)
    if not diversion:
        set_score("Behavioral Health Diversion", cap=3.0)

    # Caller management
    if not kept_on_line or not clear_next:
        set_score("Caller Management", cap=2.0)

    # Information completeness
    completeness_hits = sum(
        bool(info.get(k))
        for k in [
            "time_estimate_provided",
            "individual_description_provided",
            "number_of_individuals_affected_provided",
            "substances_or_paraphernalia_observed_provided",
        ]
    )
    if completeness_hits <= 1:
        set_score("Information Completeness", cap=2.0)
    elif completeness_hits == 2:
        set_score("Information Completeness", cap=3.0)

    return dimension_scores


def _metadata_from_dict(call_metadata: Dict[str, Any]) -> CallMetadata:
    return CallMetadata(
        call_id=str(call_metadata["call_id"]),
        date=str(call_metadata["date"]),
        operator=str(call_metadata["operator"]),
        duration=str(call_metadata["duration"]),
        call_type=str(call_metadata["call_type"]),
    )


def grade_call_from_transcript(
    *,
    transcript_text: str,
    call_metadata: Dict[str, Any],
    nvidia_api_key: str,
    model: str,
) -> CallGradingReport:
    metadata = _metadata_from_dict(call_metadata)

    step1_messages = _step1_extract_evidence_prompt(
        transcript_text=transcript_text,
        call_type_hint=metadata.call_type,
    )
    step1_raw = call_nvidia_chat_completions(
        api_key=nvidia_api_key,
        model=model,
        messages=step1_messages,
        max_tokens=900,
        temperature=0.2,
    )
    evidence_json = parse_json_object(step1_raw)

    step2_messages = _step2_scorecard_prompt(
        transcript_text=transcript_text,
        call_type_hint=metadata.call_type,
        evidence_json=evidence_json,
    )
    step2_raw = call_nvidia_chat_completions(
        api_key=nvidia_api_key,
        model=model,
        messages=step2_messages,
        max_tokens=1100,
        temperature=0.0,
    )
    scorecard_json = parse_json_object(step2_raw)

    # Standardize/correct the model's per-dimension scores with deterministic rules.
    if isinstance(scorecard_json.get("dimension_scores"), list):
        ds_map: Dict[str, Dict[str, Any]] = {}
        for row in scorecard_json["dimension_scores"]:
            if isinstance(row, dict) and "name" in row:
                ds_map[str(row["name"])] = row
        ds_map = _apply_standardization_rules(ds_map, evidence_json, metadata.call_type)
        # Rehydrate list in rubric order.
        ordered = []
        for d in DIMENSIONS:
            if d.name in ds_map:
                ordered.append(ds_map[d.name])
        scorecard_json["dimension_scores"] = ordered

    # Convert LLM output into structured report.
    report = parse_scorecard(scorecard_json, metadata=metadata)
    return report

